#ifndef WK_COMMON_SPECIAL_KEY_H_
#define WK_COMMON_SPECIAL_KEY_H_

#include <stdint.h>

typedef uint8_t SpecialKey;
enum
{
    SPECIAL_KEY_NONE,
    SPECIAL_KEY_LEFT,
    SPECIAL_KEY_RIGHT,
    SPECIAL_KEY_UP,
    SPECIAL_KEY_DOWN,
    SPECIAL_KEY_TAB,
    SPECIAL_KEY_SPACE,
    SPECIAL_KEY_RETURN,
    SPECIAL_KEY_DELETE,
    SPECIAL_KEY_BS,
    SPECIAL_KEY_ESCAPE,
    SPECIAL_KEY_HOME,
    SPECIAL_KEY_PAGE_UP,
    SPECIAL_KEY_PAGE_DOWN,
    SPECIAL_KEY_END,
    SPECIAL_KEY_BEGIN,
    SPECIAL_KEY_F1,
    SPECIAL_KEY_F2,
    SPECIAL_KEY_F3,
    SPECIAL_KEY_F4,
    SPECIAL_KEY_F5,
    SPECIAL_KEY_F6,
    SPECIAL_KEY_F7,
    SPECIAL_KEY_F8,
    SPECIAL_KEY_F9,
    SPECIAL_KEY_F10,
    SPECIAL_KEY_F11,
    SPECIAL_KEY_F12,
    SPECIAL_KEY_F13,
    SPECIAL_KEY_F14,
    SPECIAL_KEY_F15,
    SPECIAL_KEY_F16,
    SPECIAL_KEY_F17,
    SPECIAL_KEY_F18,
    SPECIAL_KEY_F19,
    SPECIAL_KEY_F20,
    SPECIAL_KEY_F21,
    SPECIAL_KEY_F22,
    SPECIAL_KEY_F23,
    SPECIAL_KEY_F24,
    SPECIAL_KEY_F25,
    SPECIAL_KEY_F26,
    SPECIAL_KEY_F27,
    SPECIAL_KEY_F28,
    SPECIAL_KEY_F29,
    SPECIAL_KEY_F30,
    SPECIAL_KEY_F31,
    SPECIAL_KEY_F32,
    SPECIAL_KEY_F33,
    SPECIAL_KEY_F34,
    SPECIAL_KEY_F35,
    SPECIAL_KEY_AUDIO_VOL_DOWN,
    SPECIAL_KEY_AUDIO_VOL_MUTE,
    SPECIAL_KEY_AUDIO_VOL_UP,
    SPECIAL_KEY_AUDIO_PLAY,
    SPECIAL_KEY_AUDIO_STOP,
    SPECIAL_KEY_AUDIO_PREV,
    SPECIAL_KEY_AUDIO_NEXT,
    SPECIAL_KEY_LAST,
};

const char* specialKeyLiteral(SpecialKey special);
const char* specialKeyRepr(SpecialKey special);

#endif /* WK_COMMON_SPECIAL_KEY_H_ */
